### ISSUE TITLE
Encoding error leads to faulty import

### ISSUE THREAD

**Issue by pratikdas026** [dgg32/doctorai_synthea#6]
![image](https://user-images.githubusercontent.com/59295113/190409430-bb55cedf-060c-46b2-a4a1-39410b4f53c3.png)

Faced this issue while importing the (.csv) files using the script (config.yml) under synthea_files.
As a result of this error, the resultant schema is inaccurate and a major chunk of data ended up not being imported.

Any response is appreciated, thank you!

**Comment by dgg32** [comment]
Hi, @pratikdas026 which step is this please?

**Comment by pratikdas026** [comment]
Hi,
I referred to your article ([https://medium.com/codex/develop-doctor-ai-with-synthetic-patient-data-from-synthea-5c2410b08d51](url)) and faced this issue while importing the data using pyingest. 

Specifically, while running the _python ingest.py [path_to_config.yml]_ command.

Thank you for your response.

**Comment by dgg32** [comment]
Have you run 

./run_synthea -p

First? Could you please show the outputs of that command?

**Comment by pratikdas026** [comment]
I did run it. Since I didn't save the output then, let me re-run it and revert it to you.

**Comment by pratikdas026** [comment]
I re-ran the entire thing and let me walk you through each step in order.

Having downloaded all the required repositories, I downloaded and set up neo4j desktop.

Then I began with the data generation using synthea.

Command used: ./run_synthea -p 1000
Output:
![image](https://user-images.githubusercontent.com/59295113/191002702-9479835c-e2ef-4fa0-99f7-17f6b26c383c.png)

Having already made the changes to the config.yml file, I went forward with importing the using pyingest. However, when I ran the _pip install -r requirements.txt_ command, some warnings popped up. (attached below)

Command used: pip install -r requirements.txt
Output:
![image](https://user-images.githubusercontent.com/59295113/191003157-7fbff4e3-ab06-47e6-92d0-0a2ef5137c87.png)
![image](https://user-images.githubusercontent.com/59295113/191003172-e3db1261-32ac-4df9-a663-95dbaecc178e.png)
![image](https://user-images.githubusercontent.com/59295113/191003196-73531e85-f81d-4b09-bda4-ef78896c2abc.png)
![image](https://user-images.githubusercontent.com/59295113/191003225-86299114-b8ba-4070-b930-0db2c61eadd0.png)
![image](https://user-images.githubusercontent.com/59295113/191003287-aac31480-6d79-43f9-a06e-c8afad30ceac.png)
![image](https://user-images.githubusercontent.com/59295113/191003337-2152b648-aed9-4338-9b38-d9805f8e3159.png)

At this point, when I run the pyingest command, the same output is being produced as attached in the original post.

To provide more insight, upon checking the schema of the data, the following is what I receive. 

![image](https://user-images.githubusercontent.com/59295113/191003740-60975525-cb41-43a1-9068-0c467825ba3d.png)

N.B.: This schema was produced with the new data generated. What is peculiar is that the schema for the previously generated dataset was drastically different (presently I don't have a screenshot for that though). My concern being, since the config.yml and synthea.properties files for both the datasets are same, why does it show different schema?

Again, thank you for spending your valuable time with helping me out. Much appreciated!

**Comment by pratikdas026** [comment]
With the help of @dgg32, it was found that the "UTF-8" encoding option in the _synthea.properties_ file caused the import process to behave unexpectedly on some devices. As an alternative, one can use "ASCII" encoding just by editing line 27 of the synthea.properties file.

Anyone facing such an issue could refer to this thread to get their issue resolved. Thank you @dgg32 for the help!
